spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  config:
    import: classpath:env.yml

logging:
  level:
    org.springframework.core.LocalVariableTableParameterNameDiscoverer: error
